# Generated by Django 5.2.6 on 2025-09-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='topic',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='topic',
            field=models.ManyToManyField(related_name='newspapers', to='news.topic'),
        ),
    ]
