# Generated by Django 5.2.6 on 2025-09-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newspaper_topic_newspaper_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='topic',
        ),
        migrations.CreateModel(
            name='NewspaperTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newspaper')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.topic')),
            ],
            options={
                'unique_together': {('topic', 'newspaper')},
            },
        ),
        migrations.AddField(
            model_name='newspaper',
            name='topics',
            field=models.ManyToManyField(related_name='newspapers', through='news.NewspaperTopic', to='news.topic'),
        ),
    ]
